package com.habiba.newsapp

class countries {
    companion object{
        // no country called is***ail , removing it is a must , free Palestine
        val countryMap = mapOf(
            "us" to "United States",
            "ae" to "United Arab Emirates",
            "ar" to "Argentina",
            "at" to "Austria",
            "au" to "Australia",
            "be" to "Belgium",
            "bg" to "Bulgaria",
            "br" to "Brazil",
            "ca" to "Canada",
            "ch" to "Switzerland",
            "cn" to "China",
            "co" to "Colombia",
            "cu" to "Cuba",
            "cz" to "Czech Republic",
            "de" to "Germany",
            "eg" to "Egypt",
            "fr" to "France",
            "gb" to "United Kingdom",
            "gr" to "Greece",
            "hk" to "Hong Kong",
            "hu" to "Hungary",
            "id" to "Indonesia",
            "ie" to "Ireland",
            "in" to "India",
            "it" to "Italy",
            "jp" to "Japan",
            "kr" to "South Korea",
            "lt" to "Lithuania",
            "lv" to "Latvia",
            "ma" to "Morocco",
            "mx" to "Mexico",
            "my" to "Malaysia",
            "ng" to "Nigeria",
            "nl" to "Netherlands",
            "no" to "Norway",
            "nz" to "New Zealand",
            "ph" to "Philippines",
            "pl" to "Poland",
            "pt" to "Portugal",
            "ro" to "Romania",
            "rs" to "Serbia",
            "ru" to "Russia",
            "sa" to "Saudi Arabia",
            "se" to "Sweden",
            "sg" to "Singapore",
            "si" to "Slovenia",
            "sk" to "Slovakia",
            "th" to "Thailand",
            "tr" to "Turkey",
            "tw" to "Taiwan",
            "ua" to "Ukraine",
            "ve" to "Venezuela",
            "za" to "South Africa"
        )

    }
}